# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# #############
# master branch
# #############
# GitHub Actions
- target-branch: master
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling: (chore)"
  labels:
    - "ok-to-test"
    - "area/ci"
  groups:
    all-github-actions:
      patterns: [ "*" ]

# Main Go module
- target-branch: master
  package-ecosystem: "gomod"
  directories:
  - "/"
  - "/hack/tools"
  schedule:
    interval: "weekly"
    day: "monday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  commit-message:
    prefix: ":seedling: (chore)"
  labels:
    - "ok-to-test"
  open-pull-requests-limit: 10

## Update dockerfile
- target-branch: master
  package-ecosystem: docker
  directory: "/cluster/images/controller-manager"
  schedule:
    interval: weekly
  commit-message:
    prefix: ":seedling: (chore)"
  labels:
    - "ok-to-test"
  groups:
    all-docker-update:
      patterns: [ "*" ]

# Test Go module
- target-branch: master
  package-ecosystem: "gomod"
  directory: "/test/e2e"
  schedule:
    interval: "weekly"
    day: "tuesday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
    sigs-k8s:
      patterns: [ "sigs.k8s.io/*" ]
    onsi:
      patterns: [ "github.com/onsi/*" ]
  commit-message:
    prefix: ":seedling: (chore)"
  labels:
    - "ok-to-test"

# ##################
# release branch N
# ##################
# GitHub Actions
- target-branch: release-1.33
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling: (chore)[release-1.33]"
  labels:
    - "ok-to-test"
    - "area/ci"
  groups:
    all-github-actions:
      patterns: [ "*" ]
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"

# Main Go module
- target-branch: release-1.33
  package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  commit-message:
    prefix: ":seedling: (chore)[release-1.33]"
  labels:
    - "ok-to-test"
  open-pull-requests-limit: 5
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"

## Update dockerfile
- target-branch: release-1.33
  package-ecosystem: docker
  directory: "/cluster/images/controller-manager"
  schedule:
    interval: weekly
  commit-message:
    prefix: ":seedling: (chore)[release-1.33]"
  labels:
    - "ok-to-test"
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
  groups:
    all-docker-update:
      patterns: [ "*" ]

# Test Go module
- target-branch: release-1.33
  package-ecosystem: "gomod"
  directory: "/test/e2e"
  schedule:
    interval: "weekly"
    day: "tuesday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
    sigs-k8s:
      patterns: [ "sigs.k8s.io/*" ]
    onsi:
      patterns: [ "github.com/onsi/*" ]
  commit-message:
    prefix: ":seedling: (chore)[release-1.33]"
  labels:
    - "ok-to-test"
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"

# ################
# release branch N-1
# ################
# GitHub Actions
- target-branch: release-1.32
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling: (chore)[release-1.32]"
  labels:
    - "ok-to-test"
    - "area/ci"
  groups:
    all-github-actions:
      patterns: [ "*" ]
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"

# Main Go module
- target-branch: release-1.32
  package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  commit-message:
    prefix: ":seedling: (chore)[release-1.32]"
  labels:
    - "ok-to-test"
  open-pull-requests-limit: 5
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"

## Update dockerfile
- target-branch: release-1.32
  package-ecosystem: docker
  directory: "/cluster/images/controller-manager"
  schedule:
    interval: weekly
  commit-message:
    prefix: ":seedling: (chore)[release-1.32]"
  labels:
    - "ok-to-test"
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
  groups:
    all-docker-update:
      patterns: [ "*" ]

# Test Go module
- target-branch: release-1.32
  package-ecosystem: "gomod"
  directory: "/test/e2e"
  schedule:
    interval: "weekly"
    day: "tuesday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
    sigs-k8s:
      patterns: [ "sigs.k8s.io/*" ]
    onsi:
      patterns: [ "github.com/onsi/*" ]
  commit-message:
    prefix: ":seedling: (chore)[release-1.32]"
  labels:
    - "ok-to-test"
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"

# ##################
# release branch N-2
# ##################
# GitHub Actions
- target-branch: release-1.31
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling: (chore)[release-1.31]"
  labels:
    - "ok-to-test"
    - "area/ci"
  groups:
    all-github-actions:
      patterns: [ "*" ]
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"

# Main Go module
- target-branch: release-1.31
  package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  commit-message:
    prefix: ":seedling: (chore)[release-1.31]"
  labels:
    - "ok-to-test"
  open-pull-requests-limit: 5
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"

## Update dockerfile
- target-branch: release-1.31
  package-ecosystem: docker
  directory: "/cluster/images/controller-manager"
  schedule:
    interval: weekly
  commit-message:
    prefix: ":seedling: (chore)[release-1.31]"
  labels:
    - "ok-to-test"
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
  groups:
    all-docker-update:
      patterns: [ "*" ]

# Test Go module
- target-branch: release-1.31
  package-ecosystem: "gomod"
  directory: "/test/e2e"
  schedule:
    interval: "weekly"
    day: "tuesday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
    sigs-k8s:
      patterns: [ "sigs.k8s.io/*" ]
    onsi:
      patterns: [ "github.com/onsi/*" ]
  commit-message:
    prefix: ":seedling: (chore)[release-1.31]"
  labels:
    - "ok-to-test"
  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
